version: '3.6'

services:
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: kita
    ports:
      - "5432:5432"

  bundle:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./bundle/build/libs/bundle-rolling-all.jar:/usr/app/bundle-rolling-all.jar
      - ./startJvm.sh:/usr/app/startJvm.sh
    working_dir: /usr/app
    command: [sh, startJvm.sh,
              "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005",
              bundle-rolling-all.jar]
    ports:
      - "8070:8070"
      - "5005:5005"
    links:
      - psql:psql
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      DB_RESET: always
