version: '3.6'

services:
  psql:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: kita
    ports:
      - "5432:5432"

  manager:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./manager/build/libs:/usr/app
      - ./client/dist:/usr/app/webroot
    ports:
      - "8070:8070"
    working_dir: /usr/app
    command: [java, --enable-preview, -jar, manager-rolling-all.jar, -cluster]
    links:
      - psql:psql
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      DB_MODE: reset

  server:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./server/build/libs:/usr/app
    working_dir: /usr/app
    command: [java, --enable-preview, -jar, server-rolling-all.jar, -cluster]
    links:
      - psql:psql
    depends_on:
      - manager
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
