version: '3.1'

services:
  psql:
    image: postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: kita
    ports:
      - "5432:5432"

  caddy:
    image: caddy
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy_data:/data"
      - "./client/dist:/web"
    ports:
      - "8042:80"
    links:
      - "manager:manager"
      - "server:server"

  manager:
    image: bellsoft/liberica-openjdk-debian
    volumes:
      - "./manager/build/libs:/app"
    working_dir: "/app"
    command: ["java", "--enable-preview", "-jar", "manager-rolling-all.jar", "-cluster"]
    links:
      - "psql:psql"
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita

  server:
    image: bellsoft/liberica-openjdk-debian
    volumes:
      - "./server/build/libs:/app"
    working_dir: "/app"
    command: ["java", "--enable-preview", "-jar", "server-rolling-all.jar", "-cluster"]
    links:
      - "psql:psql"
      - "manager:manager"
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      ENDPOINT: /server/
