version: '3.6'

services:
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8070:80"

  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: kita
    ports:
      - "5432:5432"

  manager:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./manager/build/libs/manager-rolling-all.jar:/usr/app/manager-rolling-all.jar
      - ./startJvm.sh:/usr/app/startJvm.sh
    working_dir: /usr/app
    command: [sh, startJvm.sh, "", -cluster]
    links:
      - psql:psql
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      DB_RESET: always
      ARTIFACT_NAME: manager-rolling-all.jar

  server:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./server/build/libs/server-rolling-all.jar:/usr/app/server-rolling-all.jar
      - ./startJvm.sh:/usr/app/startJvm.sh
    working_dir: /usr/app
    command: [sh, startJvm.sh, "", -cluster]
    links:
      - psql:psql
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      ARTIFACT_NAME: server-rolling-all.jar

  bundle:
    image: bellsoft/liberica-openjdk-debian:19
    volumes:
      - ./bundle/build/libs/bundle-rolling-all.jar:/usr/app/bundle-rolling-all.jar
      - ./startJvm.sh:/usr/app/startJvm.sh
    working_dir: /usr/app
    command: [sh, startJvm.sh, "", -cluster]
    links:
      - psql:psql
    environment:
      PGHOST: psql
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: kita
      ARTIFACT_NAME: bundle-rolling-all.jar
